###################################################################################################

- name : middleware | admin | users

  hosts: all:!middleware-database-nodes   ## This will apply to all nodes part of the WSO2 server set (WSO2, Jenkins, Bind, NTP etc) APART from the middleware-database-nodes
  sudo : true

  pre_tasks:
    - local_action: stat path='{{ inventory_dir }}/group_vars/{{ pipeline_env }}'
      become: false
      register: wso2_extra_vars
      tags:
        - always

    - name: "Include environment variables"
      include_vars: '{{ inventory_dir }}/group_vars/{{ pipeline_env }}'
      when: wso2_extra_vars.stat.exists
      tags:
        - always

  roles:

    - role: middleware/wso2/adminusers

  tags:
    - wso2
    - additional_admin_users

###################################################################################################
